name: map_picker_flutter
description: Get the address quickly and easily from Google Map in Web, Desktop and Mobile.
version: 1.0.0+2
homepage: https://github.com/Bestfastfire/map_picker_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^2.5.0
  rxdart: ^0.25.0
  latlng: ^0.1.0
  dio: ^3.0.10
  map: ^0.3.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
